export default {
    DEFAULT: 'DEFAULT',
    ANALYSIS_1: 'ANALYSIS_1',
    ANALYSIS_2: 'ANALYSIS_2',
    ANALYSIS_3: 'ANALYSIS_3',
    ANALYSIS_4: 'ANALYSIS_4',
    ANALYSIS_5: 'ANALYSIS_5',
    ANALYSIS_6: 'ANALYSIS_6'
}