export default {
  DEFAULT: "DEFAULT",
  CANSLIM_STOCKS: "CANSLIM_STOCKS",
  WATCHING_STOCKS: "WATCHING_STOCKS",
  NEED_STUDY_STOCKS: "NEED_STUDY_STOCKS",
  QUICK_FILTER_STOCKS: "QUICK_FILTER_STOCKS"
};
