export default {
  DEFAULT: "DEFAULT",
  CANSLIM_STOCKS: "CANSLIM_STOCKS",
  WATCHING_STOCKS: "WATCHING_STOCKS",
  NEED_STUDY_STOCKS: "NEED_STUDY_STOCKS",
  QUICK_FILTER_STOCKS: "QUICK_FILTER_STOCKS",
  CO_PHIEU_DAU_CO: "CO_PHIEU_DAU_CO",
  CO_PHIEU_GIA_TRI: "CO_PHIEU_GIA_TRI",
  ALL: "ALL",
};
